### PR TITLE
add some features

### PR DESCRIPTION
**Pull request by nat9h**
added bing image, simi (with teach), and gpt (turbo and uncen_chat)

### CODE REVIEW

**Comment by xct007** [comment]
Mok

**Comment by nat9h** [comment]
> Mok

jink wkwk

**Comment by xct007** [comment]
> > Mok
> 
> jink wkwk

Jangan di `throw`
```javascript
if (!status) {
   throw new Error(message);
}
```

Ubah return
```javascript
if (!status) {
   return m.reply(message)
}
```

Kalo di `throw` nanti bakal muncul pesan di `failed`

**Comment by nat9h** [comment]
> > > Mok
> > 
> > 
> > jink wkwk
> 
> Jangan di `throw`
> 
> ```js
> if (!status) {
>    throw new Error(message);
> }
> ```
> 
> Ubah return
> 
> ```js
> if (!status) {
>    return m.reply(message)
> }
> ```
> 
> Kalo di `throw` nanti bakal muncul pesan di `failed`

woke ganti dulu

**Comment by nat9h** [comment]
> > > Mok
> > 
> > 
> > jink wkwk
> 
> Jangan di `throw`
> 
> ```js
> if (!status) {
>    throw new Error(message);
> }
> ```
> 
> Ubah return
> 
> ```js
> if (!status) {
>    return m.reply(message)
> }
> ```
> 
> Kalo di `throw` nanti bakal muncul pesan di `failed`

done mok

**Comment by xct007** [comment]
> > > > Mok
> > > 
> > > 
> > > jink wkwk
> > 
> > 
> > Jangan di `throw`
> > ```js
> > if (!status) {
> >    throw new Error(message);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ubah return
> > ```js
> > if (!status) {
> >    return m.reply(message)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Kalo di `throw` nanti bakal muncul pesan di `failed`
> 
> done mok

**Approved**

**Review by xct007 — APPROVED** [review]

**Pull request merged**
